[ETP-473]Tests/v2 snapshots part 2
moderntribe/event-tickets pull request #1792
Opened 2020-09-30 13:25 UTC by rafsuntaskin

[ET-473]

Adding more tests over the previous PR.

2020-10-02 10:25 UTC, juanfra requested changes
This is great Rafsun! Just left a couple comments.

2020-10-02 11:09 UTC, rafsuntaskin commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
> +		$this->assertContains( 'tribe__details__content1', $html );
Yes,  this is intentional. Currently, we have this class like this only for modal: https://github.com/moderntribe/event-tickets/blob/06eb5ae459448565e7bf38d96318a767da012906/src/views/v2/tickets/item/content/description.php#L31

So, I just double-checked this class where it should be present for the `is_modal = true` case.

2020-10-02 13:32 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
> +		$this->assertContains( 'tribe__details__content1', $html );
Shouldn't it be `tribe__details__content__modal` then? If it's concatenating a `1` I guess that the ternary is not doing what it supposed to do.

2020-10-06 15:33 UTC, rafsuntaskin commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
> +		$this->assertContains( 'tribe__details__content1', $html );
Yes, this needs to be fixed in a separate PR as I am not sure if changing the will impact any CSS or not. So, I just went with the snapshots for the current output.
Currently, this is happening in the stable version: http://p.tri.be/rct8Kd

2020-10-06 15:40 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
> +		$this->assertContains( 'tribe__details__content1', $html );
Ok, we should be ticketing this, maybe we can tell Leo and be sure we don't miss this in the future by creating a ticket, referencing these comments.

2020-10-06 15:42 UTC, juanfra submitted a review, later dismissed
LGTM 😎

2020-10-07 05:07 UTC, sc0ttkclark submitted a review, later dismissed

2020-10-07 05:08 UTC, sc0ttkclark commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
> +		$this->assertContains( 'tribe__details__content1', $html );
New ticket for this +1

2020-10-07 19:05 UTC, rafsuntaskin commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
> +		$this->assertContains( 'tribe__details__content1', $html );
Created ticket:
https://moderntribe.atlassian.net/browse/ET-920

2020-10-07 21:26 UTC, sc0ttkclark approved these changes

2020-10-07 21:27 UTC, merged