[ETP-473] Tests/v2 snapshots Part 3
moderntribe/event-tickets pull request #1793
Opened 2020-10-01 08:32 UTC by rafsuntaskin

[ETP-473]

Adding Tests for 'Ticket/Item/Extra'

2020-10-01 08:33 UTC, tr1b0t reviewed
:no_entry_sign: 1 error(s)

2020-10-01 08:33 UTC, tr1b0t commented on src/views/v2/tickets/item/extra/price.php
> + * @var Tribe__Tickets__Commerce__Currency $currency	                The Currency Object
:no_entry_sign: Spaces must be used for mid-line alignment; tabs are not allowed

<sub>hash: dd1236ee81cefe1b9726d425adecffe2</sub>

2020-10-02 10:37 UTC, juanfra requested changes
Great stuff!

2020-10-02 10:37 UTC, juanfra commented on src/views/v2/tickets/item/extra/price.php
> + * @var Tribe__Tickets__Ticket_Object $post_id       The Post object ID.
I think this should be `int`.

2020-10-02 10:37 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/QuantityTest.php
> +		// Threshold is less than the set capacity of 20
```suggestion
		// Threshold is less than the set capacity of 20.
```

2020-10-02 10:37 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/QuantityTest.php
> +		// Threshold is greater than the set capacity of 20
```suggestion
		// Threshold is greater than the set capacity of 20.
```

2020-10-02 10:37 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/UnlimitedTest.php
> +		// set a fixed capacity
```suggestion
		// set a fixed capacity.
```

2020-10-02 10:37 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/PriceTest.php
> +		// Set price suffix
```suggestion
		// Set price suffix.
```

2020-10-02 10:37 UTC, juanfra commented on tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/PriceTest.php
> +		// Make sure we have suffix block
```suggestion
		// Make sure we have suffix block.
```

2020-10-07 05:08 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/available.php
> + * @var Tribe__Tickets__Ticket_Object    $ticket The Ticket Object
```suggestion
 * @var Tribe__Tickets__Editor__Template $this The Template Object.
 * @var Tribe__Tickets__Ticket_Object    $ticket The Ticket Object.
```

2020-10-07 05:08 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/available/quantity.php
> + * @var int $threshold                         The threshold value to show or hide quantity available
```suggestion
 * @var Tribe__Tickets__Editor__Template $this The Template Object.
 * @var Tribe__Tickets__Ticket_Object $ticket  The Ticket Object.
 * @var int $threshold                         The threshold value to show or hide quantity available.
```

2020-10-07 05:09 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/available/unlimited.php
> + * @var int $threshold                         The threshold value to show or hide quantity available
```suggestion
 * @var Tribe__Tickets__Editor__Template $this The Template Object.
 * @var Tribe__Tickets__Ticket_Object $ticket  The Ticket Object.
 * @var int $threshold                         The threshold value to show or hide quantity available.
```

2020-10-07 05:09 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/available/unlimited.php
> + * @var int $show_unlimited                    allow showing of "unlimited".
```suggestion
 * @var int $show_unlimited                    Allow showing of "unlimited".
```

2020-10-07 05:09 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/price.php
> + * @var Tribe__Tickets__Ticket_Object $post_id       The Post object ID.
```suggestion
 * @var int $post_id       The Post object ID.
```

2020-10-07 05:09 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/price.php
> + * @var Tribe__Tickets__Commerce__Currency $currency The Currency Object
```suggestion
 * @var Tribe__Tickets__Commerce__Currency $currency The Currency Object.
```

2020-10-07 05:10 UTC, sc0ttkclark requested changes
Some phpdoc tweaks

2020-10-07 21:28 UTC, sc0ttkclark approved these changes

2020-10-07 21:29 UTC, merged

2020-10-07 21:29 UTC, sc0ttkclark commented on src/views/v2/tickets/item/extra/price.php
> + * @var Tribe__Tickets__Commerce__Currency $currency The Currency Object
@rafsuntaskin be sure to let the reviewer or a lead dev resolve code review comments so we can ensure nothing gets left behind.