[ET-876] Fix double RSVP capacity problem
moderntribe/event-tickets pull request #1821
Opened 2020-10-26 06:55 UTC by rafsuntaskin

[ET-876]

2020-10-26 06:57 UTC, tr1b0t reviewed
:no_entry_sign: 1 error(s)

2020-10-26 06:57 UTC, tr1b0t commented on src/template-tags/tickets.php
> +		} elseif ( ! $has_provider ) {
:no_entry_sign: is_a()? Really? Use instanceof instead.

<sub>hash: 6b79c7123cb12afe92b0af3a73cc9397</sub>

2020-10-27 15:56 UTC, sc0ttkclark commented
Needs change log

2020-10-27 16:17 UTC, bordoni requested changes
Let's get a changelog here.

2020-10-27 19:13 UTC, bordoni approved these changes

2020-10-27 19:29 UTC, sc0ttkclark approved these changes

2020-10-27 19:29 UTC, merged