[ET-957] Add warning if no commerce provider available
moderntribe/event-tickets pull request #1879
Opened 2020-11-30 12:43 UTC by rafsuntaskin

[ET-957]

Screenshot:

<img width="1235" alt="Screen Shot 2020-11-30 at 6 43 23 PM" src="https://user-images.githubusercontent.com/7523321/100611729-f6b3d600-333b-11eb-9d76-c4f94625d20c.png">

2020-11-30 12:45 UTC, tr1b0t reviewed
:no_entry_sign: 3 error(s)

2020-11-30 12:45 UTC, tr1b0t commented on src/Tribe/Commerce/Warnings.php
> +	 * Add Provider missing warning for tickets.
:no_entry_sign: Doc comment for parameter "$post_id" missing

<sub>hash: e07416325bcd02b11d397b544c332b12</sub>

2020-11-30 12:45 UTC, tr1b0t commented on src/Tribe/Commerce/Warnings.php
> +	 */
:no_entry_sign: Missing parameter name

<sub>hash: a37e520dea8a6a8f16ef02d345ae82f7</sub>

2020-11-30 12:45 UTC, tr1b0t commented on src/Tribe/Commerce/Warnings.php
> +
:no_entry_sign: A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.

<sub>hash: cc85894db7d445bd10d3f1316f7262b5</sub>

2020-11-30 16:49 UTC, sc0ttkclark requested changes
Some valid bot problems to resolve here, needs changelog

2020-12-01 18:13 UTC, tr1b0t reviewed
:no_entry_sign: 4 error(s)
:warning: 1 warning(s)

2020-12-01 18:13 UTC, tr1b0t commented on src/Tribe/Editor/Warnings.php
> +		$kb_url      = 'http://m.tri.be/1ao5';
:warning: Equals sign not aligned correctly; expected 1 space but found 6 spaces

<sub>hash: 00c9e53f0c179bf52e50a7080f21655e</sub>

2020-12-01 18:13 UTC, tr1b0t commented on src/Tribe/Editor/Warnings.php
> +				'<a href="%1$s" target="_blank" rel="noopener noreferrer">%2$s</a>',
:no_entry_sign: Multi-line function call not indented correctly; expected 12 spaces but found 16

<sub>hash: ffd46ae0d4f404755e4da9e4d397a8ce</sub>

2020-12-01 18:13 UTC, tr1b0t commented on src/Tribe/Editor/Warnings.php
> +				esc_url( $kb_url ),
:no_entry_sign: Multi-line function call not indented correctly; expected 12 spaces but found 16

<sub>hash: 482dfa51b22579e5cbfdae5637d1955e</sub>

2020-12-01 18:13 UTC, tr1b0t commented on src/Tribe/Editor/Warnings.php
> +				esc_html_x( '[Learn More]', 'Helper link in Ticket Editor', 'event-tickets' )
:no_entry_sign: Multi-line function call not indented correctly; expected 12 spaces but found 16

<sub>hash: 517f9434919a58b80b792d20f6ac89d0</sub>

2020-12-01 18:13 UTC, tr1b0t commented on src/Tribe/Editor/Warnings.php
> +		return sprintf( __( 'There is no payment gateway configured. To create tickets, you\'ll need to enable and configure an ecommerce solution. %1$s', 'event-tickets' ), $link );
:no_entry_sign: A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.

<sub>hash: 330dfc66042566d0cb543ca1f83ec305</sub>

2020-12-01 21:43 UTC, sc0ttkclark commented on src/Tribe/Editor/Warnings.php
> +		return sprintf( __( 'There is no payment gateway configured. To create tickets, you\'ll need to enable and configure an ecommerce solution. %1$s', 'event-tickets' ), $link );
```suggestion
		return wp_kses_post(
			sprintf(
				/* translators: %1$s: link to help article. */
				__( 'There is no payment gateway configured. To create tickets, you\'ll need to enable and configure an ecommerce solution. %1$s', 'event-tickets' ),
				$link
			)
		);
```

2020-12-01 21:47 UTC, sc0ttkclark approved these changes

2020-12-01 21:47 UTC, merged