[ET-690] Use dynamic tickets labels within block editor blocks
moderntribe/event-tickets pull request #2932
Opened 2024-02-16 18:54 UTC by codingmusician

### 🎫 Ticket

[ET-690] 

### 🗒️ Description

Within the block editor's we want to use the dynamic labels for the words 'Ticket', 'ticket', 'Tickets' and 'tickets'. We have PHP functions specifically for those labels that we will utilize by passing the values of those functions into the global editor config variable so that the blocks can access the values.

### 🎥 Artifacts 

https://www.loom.com/share/d2b5a2cfb67342aabf6dd3ec319da405

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-690]: https://stellarwp.atlassian.net/browse/ET-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-21 18:31 UTC, bordoni requested changes
Use decomposition for getting these variables, and a constant in the a base file and import across the board, avoid passing tons of `// ignores`.

2024-02-22 21:24 UTC, codingmusician commented on src/Tickets/Blocks/Ticket/app/editor/container-content/attendee-collection/iac-setting/template.js
> +							tribe_editor_config.tickets.ticketLabels.ticket.singular_lowercase // eslint-disable-line camelcase, no-undef, prettier/prettier
@bordoni I opted to create a `constants.js` folder for each block so the constant could be imported into the component.

2024-02-23 20:43 UTC, bordoni requested changes
Dont create a new file.
Check: `plugins/event-tickets/src/modules/data/blocks/ticket/constants.js`

2024-02-26 16:56 UTC, bordoni approved these changes

2024-02-26 17:26 UTC, merged